#spring.datasource.url=jdbc:postgresql://localhost:5432/coplate_db
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/coplate_db
spring.datasource.username=postgres
spring.datasource.password=ghjvgtym
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=true

logging.level.ru.ssau.tk.faible=DEBUG
logging.level.root=WARN
logging.level.org.springframework.security=DEBUG

faible.coplatebackend.secret=nf8723hiuecrvyh9834fy98cvrehjkvvrfvw4rf24v45vrsvbr43
faible.coplatebackend.lifetime=86400000